; PlatformIO Project Configuration File
; LifeLine RX Pro - ESP32 Emergency Receiver

[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7789 and ST7735 Library @ ^1.10.3
